#general
run_type: train
device: cuda
seed: 1

# Wandb
wandb:
  project_name: hw_4_invariant_networks
  prefix: sweep
  log: True

data:
  train_size: 1000
  test_size: 1000
  set_size: 3
  data_dim: 5
  output_dim: 1

architecture:
  model_type: AugmentationNetwork
  hidden_dim: 64
  num_layers: 3

training:
  batch_size: 128
  lr: 0.001
  epochs: 100
  eval_every: 100
  oot: 30




