#general
run_type: train
device: cpu
seed: 1

# Wandb
wandb:
  project_name: hw_4_invariant_networks
  prefix: sweep
  log: False

data:
  train_size: 100
  test_size: 1000
  set_size: 10
  data_dim: 5
  output_dim: 1

architecture:
  model_type: CanonizationNetwrok
  hidden_dim: 300
  num_layers: 6

training:
  batch_size: 128
  lr: 0.001
  epochs: 100000
  eval_every: 100
  oot: 30




